fallback-grpc-addr: 192.168.77.38:3030
consul:
  addr: 192.168.77.38:8500
order:
  service-name: order
  server-to-run: http
  http-addr: 192.168.77.38:8282
  grpc-addr: 192.168.77.38:5002
stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 192.168.77.38:8283
  grpc-addr: 192.168.77.38:5003
payment:
  service-name: payment
  server-to-run: http
  http-addr: 192.168.77.38:8284
  grpc-addr: 192.168.77.38:5004

rabbitmq:
  user: guest
  password: guest
  host: 192.168.77.38
  port: 5672

stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"