fallback-grpc-addr: 192.168.77.38:3030
dial-grpc-timeout: 10
prometheus:
  export_http_host: 192.168.77.38
  export_http_port: 9123
jaeger:
  url: "http://192.168.77.38:14268/api/traces"
consul:
  addr: 192.168.77.38:8500
order:
  service-name: order
  server-to-run: http
  http-addr: 192.168.77.38:8282
  grpc-addr: 192.168.77.38:5002
  metrics_export_addr: 192.168.77.38:9123
stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 192.168.77.38:8283
  grpc-addr: 192.168.77.38:5003
  metrics_export_addr: 192.168.77.38:9124
payment:
  service-name: payment
  server-to-run: http
  http-addr: 192.168.77.38:8284
  grpc-addr: 192.168.77.38:5004
  metrics_export_addr: 192.168.77.38:9125
kitchen:
  service-name: kitchen
rabbitmq:
  user: guest
  password: guest
  host: 192.168.77.38
  port: 5672
  max-retry: 3
mysql:
  user: root
  password: root
  host: 192.168.77.38
  port: 3307
  dbname: "gorder_v2"
redis:
  local:
    ip: 192.168.77.38
    port: 6379
    pool_siez: 100
    max_conn: 100
    conn_timeout: 1000
    read_timeout: 1000
    write_timeout: 100

mongo:
  user: root
  password: password
  host: 192.168.77.38
  port: 27017
  db-name: "order"
  coll-name: "order"



stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"